### PR TITLE
Add cross Scala version trait

### PR DESCRIPTION
**Pull request by joan38**
See an example of usage on [mill-git](https://github.com/joan38/mill-git/blob/master/build.sc#L42-L44)

### CODE REVIEW

**Comment by lefou** [comment]
Thanks for this pull request. I already have a cross setup in https://github.com/lefou/mill-osgi which is more based on the mill API version and can also control all mill test versions to ensure compatibility. I will also document it in the Readme. Also, I don't think we really need the extra trait.

So, please bear with me that I will not merge this.

FTR, here is the essential part of the setup: https://github.com/lefou/mill-osgi/blob/89f5f40d687142039932bf4e8e8bb131df2a7987/build.sc#L176

**Comment by joan38** [comment]
Ah that's great to tie together Scala and Mill versions, I will improve mine to do the same.
Why do you think we don't need a trait for this? The override of `millSourcePath` was non trivial to fine to me and I expect this to be a major barriere to cross testing.

**Comment by lefou** [comment]
Yeah, but the amount of required `os.up`s depends on the count of cross-parameters. Also, in case you _want_ to provide different sources for different cross-parameters, this setting can be counter-productive. Or the trait should also provide additional sources (related to the cross-paramters), like e.g. the scala cross trait adds source folders for the concrete scala version.

**Comment by lefou** [comment]
Also, adding some note about `millSourcePath` in case of `Cross` in the mill documentation seems to be a good idea.

**Pull request closed without merging**
