### PR TITLE
Support mill 0.9.x

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by lefou** [comment]
Thank you, @joan38 . But it isn't enough, as in this setup there is no disambiguation between the version for mill 0.7.0 and 0.9.0. I think it would make sense to add something like `_mill_0_7` as a prefix.

**Comment by joan38** [comment]
I figured this indeed. What about removing 0.7.x?

**Comment by lefou** [comment]
I'd rather keep it  (we also have a 0.6 version) as long as possible. You never know who uses it. And you never know the showstoppers for others to not upgrade to newer mill versions.

**Comment by lefou** [comment]
I have some spare time tonight, so I can also finish this, if that is ok for you?

**Comment by joan38** [comment]
I just pushed. I can leave it to you from this point.

**Comment by lefou** [comment]
Thank you! I hope, I can get it ready very soon.

**Pull request merged**
